from app.schemas.claim_form import (
    PrimaryInsured,
    InsuranceHistory,
    PatientDetails,
    HospitalizationDetails,
    ClaimExpenses,
    BenefitDetails,
    DocumentChecklist,
    HospitalDetails,
    Diagnosis,
    Comorbidity,
    ProcedureCode,
    PreAuthorization,
    InjuryDetails,
    DiagnosisAndTreatment,
    BankDetails,
    Declaration,
    ClaimForm,
)

CATEGORY_TO_SCHEMA = {
    "PrimaryInsured": PrimaryInsured,
    "InsuranceHistory": InsuranceHistory,
    "PatientDetails": PatientDetails,
    "HospitalizationDetails": HospitalizationDetails,
    "ClaimExpenses": ClaimExpenses,
    "BenefitDetails": BenefitDetails,
    "DocumentChecklist": DocumentChecklist,
    "HospitalDetails": HospitalDetails,
    "Diagnosis": Diagnosis,
    "Comorbidity": Comorbidity,
    "ProcedureCode": ProcedureCode,
    "PreAuthorization": PreAuthorization,
    "InjuryDetails": InjuryDetails,
    "DiagnosisAndTreatment": DiagnosisAndTreatment,
    "BankDetails": BankDetails,
    "Declaration": Declaration,
    "ClaimForm": ClaimForm,
}

CLAIM_FORM_SCHEMA = ClaimForm
