"""initial_schema_with_vector

Revision ID: 2a7f3370171e
Revises: 
Create Date: 2026-06-20 16:00:32.688262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2a7f3370171e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_code', sa.String(length=50), nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('hospital_type', sa.Enum('NETWORK', 'NON_NETWORK', name='hospitaltype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_code')
    )
    op.create_table('icd_master',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('icd_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_chronic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd_master_icd_code'), 'icd_master', ['icd_code'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_no', sa.String(length=50), nullable=False),
    sa.Column('tpa_id', sa.String(length=50), nullable=False),
    sa.Column('policy_holder_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('commencement_date', sa.Date(), nullable=False),
    sa.Column('total_sum_insured', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_sum_insured', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('room_rent_cap_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('co_pay_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_policy_no'), 'policies', ['policy_no'], unique=True)
    op.create_table('policy_beneficiaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beneficiary_relationship', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_beneficiaries_name'), 'policy_beneficiaries', ['name'], unique=False)
    op.create_index(op.f('ix_policy_beneficiaries_policy_id'), 'policy_beneficiaries', ['policy_id'], unique=False)
    op.create_table('policy_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_code', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'policy_code', 'version', name='uq_policy_identity')
    )
    op.create_index(op.f('ix_policy_docs_company_id'), 'policy_docs', ['company_id'], unique=False)
    op.create_index(op.f('ix_policy_docs_policy_code'), 'policy_docs', ['policy_code'], unique=False)
    op.create_table('policy_rules_exclusions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('icd_id', sa.Uuid(), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.Enum('EXCLUSION', 'WAITING_PERIOD', 'SUB_LIMIT', name='ruletype'), nullable=False),
    sa.Column('waiting_period_months', sa.Integer(), nullable=False),
    sa.Column('max_payout_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['icd_id'], ['icd_master.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_exclusions_policy_id'), 'policy_rules_exclusions', ['policy_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'UNDER_REVIEW', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', name='claimstatus'), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_agent_id', sa.Uuid(), nullable=True),
    sa.Column('next_step', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['policy_beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
    op.create_table('policy_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('clause_number', sa.String(length=50), nullable=True),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('section_type', sa.Enum('DEFINITION', 'EXCLUSION', 'INCLUSION', 'WAITING_PERIOD', 'SUB_LIMIT', 'COPAY', 'CONDITION', 'CLAIM_PROCEDURE', 'GENERAL', name='sectiontype'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_clauses_policy_id'), 'policy_clauses', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_clauses_section_type'), 'policy_clauses', ['section_type'], unique=False)
    op.create_table('policy_structured_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('sum_insured', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('room_rent_limit', sa.JSON(), nullable=True),
    sa.Column('copay', sa.JSON(), nullable=True),
    sa.Column('waiting_periods', sa.JSON(), nullable=True),
    sa.Column('sub_limits', sa.JSON(), nullable=True),
    sa.Column('permanent_exclusions', sa.JSON(), nullable=True),
    sa.Column('raw_extraction', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_structured_fields_policy_id'), 'policy_structured_fields', ['policy_id'], unique=True)
    op.create_table('claim_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_financials',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('requested_hospitalization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_pre_hospitalization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_post_hospitalization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_hospitalization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_pre_hospitalization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_post_hospitalization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_approved_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('claim_medical_details',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('hospital_type', sa.Enum('NETWORK', 'NON_NETWORK', name='hospitaltype'), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=False),
    sa.Column('icd_id', sa.Uuid(), nullable=False),
    sa.Column('procedure_name', sa.String(length=255), nullable=False),
    sa.Column('room_category_used', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['icd_id'], ['icd_master.id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claim_medical_details_icd_id'), 'claim_medical_details', ['icd_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_medical_details_icd_id'), table_name='claim_medical_details')
    op.drop_table('claim_medical_details')
    op.drop_table('claim_financials')
    op.drop_table('claim_documents')
    op.drop_index(op.f('ix_policy_structured_fields_policy_id'), table_name='policy_structured_fields')
    op.drop_table('policy_structured_fields')
    op.drop_index(op.f('ix_policy_clauses_section_type'), table_name='policy_clauses')
    op.drop_index(op.f('ix_policy_clauses_policy_id'), table_name='policy_clauses')
    op.drop_table('policy_clauses')
    op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_policy_rules_exclusions_policy_id'), table_name='policy_rules_exclusions')
    op.drop_table('policy_rules_exclusions')
    op.drop_index(op.f('ix_policy_docs_policy_code'), table_name='policy_docs')
    op.drop_index(op.f('ix_policy_docs_company_id'), table_name='policy_docs')
    op.drop_table('policy_docs')
    op.drop_index(op.f('ix_policy_beneficiaries_policy_id'), table_name='policy_beneficiaries')
    op.drop_index(op.f('ix_policy_beneficiaries_name'), table_name='policy_beneficiaries')
    op.drop_table('policy_beneficiaries')
    op.drop_index(op.f('ix_policies_policy_no'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_icd_master_icd_code'), table_name='icd_master')
    op.drop_table('icd_master')
    op.drop_table('hospitals')
    op.drop_table('companies')
    # ### end Alembic commands ###
