INITIAL_STATE = {
    "document_text": None,
    "primary_insured": {
        "policy_no": None,
        "tpa_id": None,
        "policy_holder_name": "",
        "address": None,
        "city": None,
        "state": None,
        "pin_code": None,
        "phone": None,
        "email": None,
    },
    "insurance_history": {
        "other_medical_insurance": None,
        "commencement_without_break_date": None,
        "insurance_company_name": None,
        "previous_policy_no": None,
        "sum_insured": None,
        "hospitalized_in_last_four_years": None,
    },
    "patient_details": {
        "patient_name": None,
        "relationship_to_policy_holder": "self",
        "gender": None,
        "age": None,
        "date_of_birth": None,
        "occupation": None,
        "room_category": None,
        "hospitalization_reason": None,
        "system_of_medicine": None,
    },
    "prescriptions": [
        {
            "prescription_id": "",
            "date": "",
            "prescriber_name": "",
            "registration_no": "",
            "clinic": "",
            "medications": [
                {
                    "name": "",
                    "strength": "",
                    "form": "",
                    "dosage": "",
                    "frequency": "",
                    "duration_days": 0,
                    "instructions": "",
                }
            ],
            "notes": "",
            "file": "",
        }
    ],
    "hospital_details": {
        "hospital_name": None,
        "hospital_id": None,
        "hospital_address": None,
        "hospital_type": None,
        "doctor_name": None,
        "doctor_qualification": None,
        "doctor_registration_no": None,
        "diagnosis": None,
        "procedure": None,
        "treating_doctor": None,
    },
    "hospitalization_details": {
        "date_of_admission": None,
        "time_of_admission": None,
        "date_of_discharge": None,
        "time_of_discharge": None,
        "type_of_admission": None,
        "status_at_discharge": None,
    },
    "bank_details": {
        "beneficiary_name": None,
        "bank_name": None,
        "account_no": None,
        "ifsc": None,
    },
    "claim_details": {
        "hospitalization_expenses": None,
        "pre_hospitalization_expenses": None,
        "pre_hospitalization_period_days": None,
        "post_hospitalization_expenses": None,
        "post_hospitalization_period_days": None,
        "health_checkup_cost": None,
        "ambulance_charges": None,
        "other_expenses": None,
        "total_expenses": None,
    },
    "benefit_details": {
        "hospital_daily_cash": None,
        "surgical_cash": None,
        "critical_illness_benefit": None,
        "convalescence_benefit": None,
        "pre_post_lump_sum_benefit": None,
        "other_benefits": None,
        "total_lump_sum_benefit": None,
    },
    "docs_checklist": {
        "claim_form_submitted": None,
        "intimation_letter_submitted": None,
        "hospital_main_bill_submitted": None,
        "hospital_breakup_bill_submitted": None,
        "payment_receipt_submitted": None,
        "discharge_summary_submitted": None,
        "doctor_prescription_submitted": None,
        "investigation_request_submitted": None,
        "investigation_reports_submitted": None,
        "operation_theatre_notes_submitted": None,
        "ecg_submitted": None,
        "pharmacy_bill_submitted": None,
        "other_documents_submitted": None,
    },
    "policy_record": {
        "policy_no": "",
        "tpa_id": None,
        "policy_holder_name": "",
        "active": False,
        "start_date": None,
        "end_date": None,
        "waiting_period_days": None,
        "sum_insured": 0.0,
        "room_rent_cap_per_day": None,
        "co_pay_percentage": None,
        "exclusions": [],
        "covered_icd_codes": [],
        "covered_conditions": [],
    },
    "verification": {
        "user": {"passed": False, "reason": None},
        "policy": {"passed": False, "reason": None},
        "patient": {"passed": False, "reason": None},
        "documents": {"passed": False, "reason": None},
        "overall_verified": False,
    },
    "fraud_score": 0.0,
    "fraud_flags": [],
    "final_decision": None,
    "rejection_reason": None,
    "approved_amount": None,
    "final_report": {},
    "audit_summary": {},
    "current_agent": None,
    "next_step": "data_extraction",
    "workflow_history": [],
}

######################### .EXRACTED_DATA.  #########################
EXRACTED_DATA = {
    "document_text": None,
    "primary_insured": {
        "policy_no": "POL-99887766",
        "tpa_id": "TPA-4521",
        "policy_holder_name": "Ram Yadav",
        "address": "Flat 12, Sunrise Apartments, MG Road",
        "city": "Bangalore",
        "state": "Karnataka",
        "pin_code": "560001",
        "phone": None,
        "email": "ram.yadav@gmail.com",
    },
    "insurance_history": {
        "other_medical_insurance": True,
        "commencement_without_break_date": "2020-10-10",
        "insurance_company_name": "Star Health",
        "previous_policy_no": "POL-88997766",
        "sum_insured": 1000000.0,
        "hospitalized_in_last_four_years": True,
    },
    "patient_details": {
        "patient_name": "Sita Yadav",
        "relationship_to_policy_holder": "spouse",
        "gender": None,
        "age": None,
        "date_of_birth": None,
        "occupation": None,
        "room_category": "single_occupency",
        "hospitalization_reason": "illness",
        "system_of_medicine": "allopathy",
    },
    "prescriptions": [
        {
            "prescription_id": "RX-2026-0001",
            "date": "2026-05-19",
            "prescriber_name": "Dr. S. Mehta",
            "registration_no": "MCI/12-45678",
            "clinic": "Green Valley Hospital",
            "medications": [
                {
                    "name": "Cefuroxime",
                    "strength": "500 mg",
                    "form": "tablet",
                    "dosage": "1 tablet",
                    "frequency": "twice a day",
                    "duration_days": 5,
                    "instructions": "after food",
                },
                {
                    "name": "Paracetamol",
                    "strength": "500 mg",
                    "form": "tablet",
                    "dosage": "1 tablet",
                    "frequency": "as needed",
                    "duration_days": 3,
                    "instructions": "",
                },
            ],
            "notes": "Complete antibiotic course",
            "file": "prescription_20260519.pdf",
        }
    ],
    "hospital_details": {
        "hospital_name": "Green Valley Hospital",
        "hospital_id": "HED-MUM-HOS-0421",
        "hospital_address": "12 Health Park, Sector 5, Bangalore",
        "hospital_type": "network",
        "doctor_name": "Jhatka Vaid",
        "doctor_qualification": "MD",
        "doctor_registration_no": "MCI/12-45678",
        "diagnosis": "Acute appendicitis",
        "procedure": "Laparoscopic appendectomy",
        "treating_doctor": "Dr. S. Mehta",
    },
    "hospitalization_details": {
        "date_of_admission": "2026-05-20",
        "time_of_admission": None,
        "date_of_discharge": "2026-05-24",
        "time_of_discharge": None,
        "type_of_admission": None,
        "status_at_discharge": None,
    },
    "bank_details": {
        "beneficiary_name": "Sita Yadav",
        "bank_name": "ICICI Bank",
        "account_no": "987654321098",
        "ifsc": "ICIC0000456",
    },
    "claim_details": {
        "hospitalization_expenses": 50000.0,
        "pre_hospitalization_expenses": 10200.0,
        "pre_hospitalization_period_days": 2,
        "post_hospitalization_expenses": 5000.0,
        "post_hospitalization_period_days": 1,
        "health_checkup_cost": 4040.0,
        "ambulance_charges": 6700.0,
        "other_expenses": 0.0,
        "total_expenses": 71940.0,
    },
    "benefit_details": {
        "hospital_daily_cash": 0.0,
        "surgical_cash": 0.0,
        "critical_illness_benefit": 0.0,
        "convalescence_benefit": 0.0,
        "pre_post_lump_sum_benefit": 0.0,
        "other_benefits": 0.0,
        "total_lump_sum_benefit": 0.0,
    },
    "docs_checklist": {
        "claim_form_submitted": True,
        "intimation_letter_submitted": True,
        "hospital_main_bill_submitted": True,
        "hospital_breakup_bill_submitted": True,
        "payment_receipt_submitted": True,
        "discharge_summary_submitted": True,
        "doctor_prescription_submitted": True,
        "investigation_request_submitted": True,
        "investigation_reports_submitted": True,
        "operation_theatre_notes_submitted": True,
        "ecg_submitted": True,
        "pharmacy_bill_submitted": True,
        "other_documents_submitted": True,
    },
    "policy_record": {
        "policy_no": "POL-99887766",
        "tpa_id": "TPA-4521",
        "policy_holder_name": "Ram Yadav",
        "active": True,
        "start_date": None,
        "end_date": None,
        "waiting_period_days": None,
        "sum_insured": 1000000.0,
        "room_rent_cap_per_day": None,
        "co_pay_percentage": None,
        "exclusions": [],
        "covered_icd_codes": [],
        "covered_conditions": [],
    },
    "verification": {
        "user": {"passed": False, "reason": "Policy number not found"},
        "policy": {"passed": False, "reason": "Policy not found"},
        "patient": {"passed": False, "reason": "Policy not found"},
        "documents": {"passed": True, "reason": None},
        "overall_verified": False,
    },
    "fraud_score": 0.0,
    "fraud_flags": [],
    "final_decision": None,
    "rejection_reason": None,
    "approved_amount": None,
    "final_report": {},
    "audit_summary": {},
    "current_agent": None,
    "next_step": "completed",
    "workflow_history": [],
}
